# Generated by Django 4.1.3 on 2022-11-18 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('author', 'name')},
        ),
    ]
