# Generated by Django 4.1.3 on 2022-11-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author_alter_post_voter'),
        ('blog', '0006_post_hits_alter_post_author_alter_post_voter'),
    ]

    operations = [
    ]
