# Generated by Django 4.1.3 on 2022-11-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_name_and_more'),
        ('blog', '0007_merge_20221122_1843'),
    ]

    operations = [
    ]
