# Generated by Django 4.1.3 on 2022-11-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_author'),
        ('blog', '0008_merge_20221124_1730'),
    ]

    operations = [
    ]
